# Generated by Django 4.0 on 2022-05-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tester',
        ),
    ]
